output_path = "tmp/products.json"

[spreadsheet]
spreadsheet_id = "1xBpQ_7aG5TW2icZ8wDI7MLI60_iNwT0oodoS2Z6Er7Y"

[[spreadsheet.sheets]]
name = "men's_clothing"
gid = "39317466"

[[spreadsheet.sheets]]
name = "jewelry"
gid = "154127679"

[[spreadsheet.sheets]]
name = "electronics"
gid = "92713497"

[[spreadsheet.sheets]]
name = "women's_clothing"
gid = "1909018467"

[data_structure]
sheet_field = "category"

[[data_structure.fields]]
json = "id"
csv = "id"
type = "string"
required = true

[[data_structure.fields]]
json = "name"
csv = "nombre"
type = "string"
required = true

[[data_structure.fields]]
json = "price"
csv = "precio"
type = "float"
required = true

[[data_structure.fields]]
json = "description"
csv = "descripcion"
type = "string"
required = true

[[data_structure.fields]]
json = "img1"
csv = "img1"
type = "string"
required = false

[[data_structure.fields]]
json = "img2"
csv = "img2"
type = "string"
required = false
